### PR TITLE
fix speed increasing problem

### LINKED ISSUE #89: stacked players: order can change by itself lollll
put players on top of each other and wait. Sometimes top player becomes bottom player after a while

### LINKED ISSUE #90: stacked players: falling to ground very quickly
If two players are on top of each other and the top player walks away, it falls to ground quicker than gravity seems to work when jumping

### LINKED ISSUE #91: stacked players: top player can't jump
does not move upwards when unflattening

### PR DESCRIPTION
**Pull request by Akuli**
With stacked players, the speed of the top player would previously grow and grow by itself.

Fixes #91 
Fixes #90
Fixes #89

### CODE REVIEW

File: src/intersect.c [hunk 1]
```diff
@@ -67,41 +67,47 @@ static enum Intersect intersect_upper_and_lower_el(const struct Ellipsoid *upper
...
 				break;
-			case INTERSECT_SIDE:
+			case INTERSECT_EE_BOTTOM1_SIDE2:
 			{
 				Vec3 low2up = vec3_sub(upper->botcenter, lower->botcenter);
 				low2up.y = 0;
 				*mv = vec3_withlength(low2up, olap);
 				break;
 			}
+			default:
```
Comment (Akuli) [inline src/intersect.c:91]:
```suggestion
			case INTERSECT_EE_BOTTOM2_TIP1:
			case INTERSECT_EE_BOTTOM2_SIDE1:
```

File: src/intersect.c [hunk 2]
```diff
@@ -67,41 +67,47 @@ static enum Intersect intersect_upper_and_lower_el(const struct Ellipsoid *upper
...
 	}
 	return res;
 }	
 
-enum Intersect intersect_el_el(const struct Ellipsoid *el1, const struct Ellipsoid *el2, Vec3 *mv)
+enum IntersectElEl intersect_el_el(const struct Ellipsoid *el1, const struct Ellipsoid *el2, Vec3 *mv)
 {
 	if (el1->botcenter.y > el2->botcenter.y) {
 		return intersect_upper_and_lower_el(el1, el2, mv);
 	} else {
```
Comment (Akuli) [inline src/intersect.c:102]:
```suggestion
	} else {
		// swapped order, upper ellipsoid must go first
```
