### PR TITLE
Map editor improvements

### LINKED ISSUE #124: map editor zooming weird
Camera is too far up or too near or something, don't know exactly what's wrong but it just looks weird.

### LINKED ISSUE #146: map editor: tool buttons shortcuts are weird
"`w` for wall" made sense when I created the tool buttons, but I also maintain a translated version of the game, and "`w` for seinä" makes much less sense.

### PR DESCRIPTION
**Pull request by Akuli**
Fixes #124 (still not perfect, but better now)
Fixes #146

### CODE REVIEW

File: src/mapeditor.c [hunk 1]
```diff
@@ -59,7 +59,9 @@ struct MapEditor {
 	struct EllipsoidEdit enemyedits[MAX_ENEMIES];
 	struct Camera cam;
 	float zoom;
```
Comment (Akuli) [inline src/mapeditor.c:61]: I don't really like `zoom` anymore, but we can clean it later.

File: src/mapeditor.c [hunk 2]
```diff
@@ -91,15 +93,17 @@ static bool next_ellipsoid_edit_const(const struct MapEditor *ed, const struct E
...
+static void position_and_rotate_camera(struct MapEditor *ed, float rotspeed, float posspeed)
 {
-	ed->cam.angle += speed/CAMERA_FPS;
+	float d = max(8, hypotf(ed->map->xsize, ed->map->zsize));
 
-	float d = hypotf(ed->map->xsize, ed->map->zsize);
-	clamp_float(&d, 8, HUGE_VALF);
+	ed->cam.angle += rotspeed/CAMERA_FPS;
+	ed->campos += posspeed/CAMERA_FPS;
+	clamp_float(&ed->campos, 1, d+2);
```
Comment (Akuli) [inline src/mapeditor.c:102]: `1` is too close.

File: src/mapeditor.c [hunk 3]
```diff
@@ -91,15 +93,17 @@ static bool next_ellipsoid_edit_const(const struct MapEditor *ed, const struct E
...
 
-	Vec3 tocamera = vec3_mul_float((Vec3){ 0, 0.5f, 0.7f }, d / ed->zoom);
+	Vec3 tocamera = vec3_mul_float((Vec3){ 0, 0, 0.7f }, ed->campos / ed->zoom);
```
Comment (Akuli) [inline src/mapeditor.c:104]:
```suggestion
	Vec3 tocamera = { 0, 0.5f*d/ed->zoom, 0.7f*ed->campos/ed->zoom };
```

File: src/mapeditor.c [hunk 4]
```diff
@@ -91,15 +93,17 @@ static bool next_ellipsoid_edit_const(const struct MapEditor *ed, const struct E
...
 	vec3_apply_matrix(&tocamera, mat3_rotation_xz(ed->cam.angle));
+	tocamera.y = 0.5f * d / ed->zoom;
```
Comment (Akuli) [inline src/mapeditor.c:106]:
```suggestion
```
