### PR TITLE
Map editor: tool buttons and new mouse/keyboard behaviour

### LINKED ISSUE #76: map editor: add enemy button doesn't work when nothing selected

### LINKED ISSUE #105: map editor drag and drop rewrite
Would be nice to mouse-drag things from the side into the map, and on the side, also see how many items remain so you're aware of max number of each thing.

### PR DESCRIPTION
**Pull request by Akuli**
Fixes #105 
Fixes #76 

- [x] merge #115 
- [x] use correct image for wall
- [x] fix bug with moving on top of existing walls/ellipsoids
- [x] delete temporary thingy that makes it start in chooser
- [x] figure out why adding enemy is slow (because key release)
- [x] MOUSE: rely on the tool more with selection, re-select when switching tool (currently hard to select wall, even with wall tool on, if many enemies)
- [x] KEYBOARD: rely on the tool more with selection, re-select when switching tool (currently hard to select wall, even with wall tool on, if many enemies)

### CODE REVIEW

File: src/button.h [hunk 1]
```diff
@@ -7,16 +7,18 @@ enum ButtonFlags {
...
+	BUTTON_DISABLED = 0x80,
 };
-#define BUTTON_ALLFLAGS (BUTTON_TINY | BUTTON_SMALL | BUTTON_BIG | BUTTON_VERTICAL | BUTTON_PRESSED | BUTTON_DISABLED)
+#define BUTTON_ALLFLAGS 0xff
 
 struct Button {
 	// imgpath image and text are drawn on top of a generic button background image
 	const char *imgpath;
-	const char *text;
+	char text[100];
```
Comment (Akuli) [inline src/button.h:21]: This change is now unnecessary.

File: src/mapeditor.c [hunk 2]
```diff
@@ -416,6 +433,28 @@ static void move_selected_ellipsoid(struct MapEditor *ed, int x, int z)
 	map_save(ed->map);
 }
 
+static struct MapCoords wall_to_square(const struct Map *map, const struct Wall *w, int dx, int dz)
+{
+	SDL_assert(abs(dx) <= 1 && abs(dz) <= 1);
```
Comment (Akuli) [inline src/mapeditor.c:438]:
```suggestion
	SDL_assert(abs(dx) <= 1 && abs(dz) <= 1 && !(dx && dz));
```

File: src/mapeditor.c [hunk 3]
```diff
@@ -102,20 +114,30 @@ static struct Wall *find_wall_from_map(const struct Wall *w, struct Map *map)
 	return NULL;
 }
 
-static void add_wall(struct MapEditor *ed)
+static struct EllipsoidEdit *find_ellipsoid_edit_for_square(struct MapEditor *ed, struct MapCoords square)
```
Comment (Akuli) [inline src/mapeditor.c:117]: Should check if this function has other places where it could be used.
